services:
  - type: web
    name: marco-pharma
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: marco-pharma-mysql
          property: connectionString

databases:
  - name: marco-pharma-mysql
    plan: free
    databaseName: marphar
    user: marco_pharma_user
    engine: mysql
